
def make_plots(specs_json,cache_dir):
    f = open(specs_json)
    try:
        spec = json.load(f)
    except ValueError as err:
        print("Tests file is not a valid JSON file. Please double check syntax.")
        exit()
    f.close()
    datasets = listdir(cache_dir)
    for dataset in datasets:
        for num_updates in spec['num_updates']:
            for method in listdir(normpath(join(cache_dir,dataset))):
                for dir in listdir(normpath(join(cache_dir,dataset,method))):
                    pass








if __name__ == "__main__":
    
    import argparse
    import json
    from os import listdir,normpath,join

    arg_parser = argparse.ArgumentParser(description="Create plots for comparing covariance errors across methods for specified numbers of updates and k dimension")
    
    arg_parser.add_argument(
        "--cache_dir",
        "-c",
        dest="cache_dir",
        required=True,
        help="Specifies path to cache folder generated by run_tests.py that contains all the covariance error data"
    )
    arg_parser.add_argument(
        "--specs_json",
        "-s",
        dest="specs_json",
        required=True,
        help="Path to json file containing list of tuples specifying which number of updates to create plots for"
    )
    
    args = arg_parser.parse_args()
    
    make_plots(args.specs_json, args.cache_dir)